language: python
python:
before_install: 
    - sudo pip install --upgrade pip
install:
    - sudo pip install -r requirements.txt
before_script: 
    - cd AjoudongBE
script:
- python manage.py test

language: android
jdk: oraclejdk8
android:
    components:
        - tools
        - android-27
        - build-tools-29.0.3
before_script:
    - cd AjouDongFE
script:
    - ./gradlew build connectedCheck

notifications:
    slack: swcapposturn:qW81nIoC5VXTF6TgjIqqE8bG
