language: python
python:
    - "3.6"
env:
    - DJANGO_VERSION==3.0.4
install:
    - sudo pip install -r requirements.txt
    - sudo pip install Django=$DJANGO_VERSION
before_script: 
    - cd AjoudongBE
script:
- python manage.py test

language: android
jdk: oraclejdk8
android:
    components:
        - tools
        - android-27
        - build-tools-29.0.3
before_script:
    - cd ..
    - cd AjouDongFE
script:
    - ./gradlew build connectedCheck

notifications:
    slack: swcapposturn:qW81nIoC5VXTF6TgjIqqE8bG
