language: python
python:
  -"3.7.3"
env:
    - DJANGO_VERSION==2.2.5
install:
    - pip3 install -q Django=$DJANGO_VERSION
script:
  - python manage.py test
notifications:
  slack: swcapposturn:qW81nIoC5VXTF6TgjIqqE8bG
