language: python
python:
    - "3.6"
env:
    - DJANGO_VERSION==3.0.4 
before_install:
    - sudo apt-get install python3 python3-pip python3-dev python3-setuptools
    - sudo pip3 install --upgrade pip
install:
    - sudo pip3 install -r requirements.txt
    - sudo pip3 install Django=$DJANGO_VERSION
before_script: 
    - cd AjoudongBE
script:
- python manage.py test
notifications:
  slack: swcapposturn:qW81nIoC5VXTF6TgjIqqE8bG
