# Generated by Django 3.0.4 on 2020-05-18 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('adsID', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('advertiserID', models.CharField(max_length=32)),
                ('adsSpace', models.IntegerField()),
                ('adsIMG', models.CharField(max_length=128)),
                ('adsView', models.IntegerField()),
                ('adsrestViews', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('clubID', models.IntegerField(primary_key=True, serialize=False)),
                ('clubName', models.CharField(max_length=32)),
                ('clubCategory', models.CharField(max_length=256)),
                ('clubIMG', models.CharField(max_length=128)),
                ('clubMajor', models.IntegerField(default=1)),
                ('clubDues', models.FloatField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventID', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('eventName', models.CharField(max_length=32)),
                ('eventDate', models.DateTimeField()),
                ('eventInfo', models.CharField(max_length=1024)),
                ('eventFAQ', models.CharField(max_length=1024)),
                ('clubID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server_app.Club')),
            ],
        ),
        migrations.CreateModel(
            name='Major_Affiliation',
            fields=[
                ('majorName', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('majorCollege', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clubTag', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('uID', models.CharField(max_length=20)),
                ('uPW', models.CharField(max_length=20)),
                ('uIMG', models.CharField(max_length=128, null=True)),
                ('uName', models.CharField(max_length=10, null=True)),
                ('uJender', models.BooleanField(default=True)),
                ('uSchoolID', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('uMajor', models.CharField(max_length=32, null=True)),
                ('uPhoneNumber', models.IntegerField(null=True)),
                ('uCollege', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAlarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newclubAlarm', models.BooleanField()),
                ('stateAlarm', models.BooleanField()),
                ('eventAlarm', models.BooleanField()),
                ('autoLogin', models.BooleanField()),
                ('unreadEvent', models.BooleanField()),
                ('uSchoolID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server_app.UserAccount')),
            ],
        ),
        migrations.CreateModel(
            name='TaggedClubList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clubID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server_app.Club')),
                ('uSchoolID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server_app.UserAccount')),
            ],
        ),
        migrations.CreateModel(
            name='markedClubList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clubID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server_app.Club')),
                ('uSchoolID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server_app.UserAccount')),
            ],
        ),
        migrations.CreateModel(
            name='ManagerAccount',
            fields=[
                ('mID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('mPW', models.CharField(max_length=20, null=True)),
                ('clubName', models.CharField(max_length=5)),
                ('clubIMG', models.CharField(max_length=128)),
                ('newbieAlarm', models.BooleanField(default=True)),
                ('clubID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server_app.Club')),
            ],
        ),
        migrations.CreateModel(
            name='EventIMG',
            fields=[
                ('eventIMGKey', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('eventIMG', models.CharField(max_length=128)),
                ('eventID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server_app.Event')),
            ],
        ),
        migrations.CreateModel(
            name='ClubStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberNumber', models.IntegerField()),
                ('menNumber', models.IntegerField()),
                ('womenNumber', models.IntegerField()),
                ('overRatio12', models.FloatField()),
                ('Ratio13', models.FloatField()),
                ('Ratio14', models.FloatField()),
                ('Ratio15', models.FloatField()),
                ('Ratio16', models.FloatField()),
                ('Ratio17', models.FloatField()),
                ('Ratio18', models.FloatField()),
                ('Ratio19', models.FloatField()),
                ('engineeringRatio', models.FloatField()),
                ('ITRatio', models.FloatField()),
                ('naturalscienceRatio', models.FloatField()),
                ('managementRatio', models.FloatField()),
                ('humanitiesRatio', models.FloatField()),
                ('socialscienceRatio', models.FloatField()),
                ('nurseRatio', models.FloatField()),
                ('clubID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server_app.Club')),
            ],
        ),
        migrations.CreateModel(
            name='ClubPromotion',
            fields=[
                ('promotionID', models.IntegerField(primary_key=True, serialize=False)),
                ('posterIMG', models.CharField(max_length=128)),
                ('clubInfo', models.CharField(max_length=4096)),
                ('clubApply', models.CharField(max_length=1024)),
                ('clubFAQ', models.CharField(max_length=2048)),
                ('clubContact', models.CharField(max_length=1024)),
                ('additionalApply', models.CharField(max_length=1024)),
                ('recruitStartDate', models.DateField()),
                ('recruitEndDate', models.DateField()),
                ('clubID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server_app.Club')),
            ],
        ),
        migrations.CreateModel(
            name='ClubMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clubID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server_app.Club')),
                ('uSchoolID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server_app.UserAccount')),
            ],
        ),
        migrations.CreateModel(
            name='ClubActivity',
            fields=[
                ('clubActivityFile', models.CharField(max_length=128)),
                ('clubActivityInfo', models.CharField(max_length=256)),
                ('clubActivityID', models.IntegerField(primary_key=True, serialize=False)),
                ('clubActivityDetail', models.CharField(max_length=2048, null=True)),
                ('clubID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server_app.Club')),
            ],
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additionalApplyContent', models.CharField(max_length=1024)),
                ('clubID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server_app.Club')),
                ('uSchoolID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server_app.UserAccount')),
            ],
        ),
        migrations.CreateModel(
            name='AppliedClubList',
            fields=[
                ('applyID', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('memberState', models.BooleanField()),
                ('clubID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server_app.Club')),
            ],
        ),
    ]
