# Generated by Django 3.0.4 on 2020-05-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manageraccount',
            name='mPW',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='uPW',
            field=models.CharField(max_length=20),
        ),
    ]
