# Generated by Django 3.0.4 on 2020-05-21 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Server_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='TaggedClubList',
        ),
    ]
