# Generated by Django 3.0.4 on 2020-05-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uID', models.CharField(max_length=20)),
                ('uPW', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
