# Generated by Django 3.0.4 on 2020-05-14 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Server_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='clubPromotion',
            fields=[
                ('promotionID', models.IntegerField(primary_key=True, serialize=False)),
                ('posterIMG', models.CharField(max_length=128)),
                ('clubInfo', models.CharField(max_length=4096)),
                ('clubApply', models.CharField(max_length=1024)),
                ('clubFAQ', models.CharField(max_length=2048)),
                ('clubContact', models.CharField(max_length=1024)),
                ('additionalApply', models.CharField(max_length=1024)),
                ('recruitStartDate', models.DateField()),
                ('recruitEndDate', models.DateField()),
                ('clubID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server_app.club')),
            ],
        ),
        migrations.CreateModel(
            name='clubActivity',
            fields=[
                ('clubActivityFile', models.CharField(max_length=128)),
                ('clubActivityInfo', models.CharField(max_length=256)),
                ('clubActivityID', models.IntegerField(primary_key=True, serialize=False)),
                ('clubID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server_app.club')),
            ],
        ),
    ]
