# Generated by Django 3.0.4 on 2020-05-24 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Server_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliedclublist',
            name='applyID',
        ),
        migrations.AddField(
            model_name='appliedclublist',
            name='uSchoolID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server_app.UserAccount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clubactivity',
            name='clubActivityID',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
