# Generated by Django 3.0.5 on 2020-05-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server_app', '0002_auto_20200507_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='majorAffiliation',
            fields=[
                ('majorName', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('majorCollege', models.CharField(max_length=20)),
            ],
        ),
    ]
