# Generated by Django 3.0.4 on 2020-05-24 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Server_app', '0002_auto_20200524_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubactivity',
            name='clubID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Server_app.Club'),
        ),
    ]
