# Generated by Django 3.0.4 on 2020-05-21 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Server_app', '0002_auto_20200521_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('clubTag', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TaggedClubList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clubID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server_app.Club')),
                ('clubTag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server_app.Tag')),
            ],
            options={
                'unique_together': {('clubID', 'clubTag')},
            },
        ),
    ]
