# Generated by Django 3.0.5 on 2020-05-10 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Server_app', '0003_majoraffiliation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='majorAffiliation',
            new_name='major_Affiliation',
        ),
    ]
