# Generated by Django 3.0.4 on 2020-05-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server_app', '0003_auto_20200524_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedclublist',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
