# Generated by Django 3.0.4 on 2020-05-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server_app', '0004_auto_20200524_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubactivity',
            name='clubActivityID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
