# Generated by Django 3.0.4 on 2020-05-31 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Server_app', '0009_auto_20200601_0143'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clubID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server_app.Club')),
                ('clubTag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server_app.Tag')),
            ],
        ),
    ]
