# Generated by Django 3.0.4 on 2020-06-02 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Server_app', '0013_auto_20200601_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedclublist',
            name='applyDate',
            field=models.DateField(null=True),
        ),
    ]
