# Generated by Django 3.0.4 on 2020-06-08 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Server_app', '0015_auto_20200602_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubactivity',
            name='clubActivityThumbnail',
        ),
        migrations.AddField(
            model_name='event',
            name='eventIMG',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.DeleteModel(
            name='EventIMG',
        ),
    ]
