# Generated by Django 3.0.4 on 2020-06-13 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Server_app', '0017_auto_20200612_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
