# Generated by Django 3.0.4 on 2020-06-16 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Server_app', '0019_auto_20200614_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='eventFAQ',
        ),
        migrations.AlterField(
            model_name='useralarm',
            name='unreadEvent',
            field=models.IntegerField(),
        ),
    ]
