# Generated by Django 3.0.4 on 2020-06-20 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Server_app', '0023_auto_20200620_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQComment',
            fields=[
                ('userID', models.IntegerField()),
                ('FAQCommentID', models.AutoField(primary_key=True, serialize=False)),
                ('FAQCommentDate', models.DateTimeField()),
                ('isAnonymous', models.BooleanField()),
                ('FAQContent', models.CharField(max_length=1024)),
                ('FAQID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server_app.FAQ')),
            ],
        ),
    ]
