# Generated by Django 3.0.4 on 2020-06-20 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Server_app', '0024_auto_20200620_2138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faqcomment',
            old_name='FAQContent',
            new_name='FAQCommentContent',
        ),
    ]
