# Generated by Django 3.0.4 on 2020-06-20 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Server_app', '0025_auto_20200620_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='clubID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server_app.Club'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faqcomment',
            name='clubID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server_app.Club'),
            preserve_default=False,
        ),
    ]
