# Generated by Django 3.0.4 on 2020-06-24 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Server_app', '0026_auto_20200620_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubstatistic',
            name='DasanRatio',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clubstatistic',
            name='InternationalRatio',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clubstatistic',
            name='MedicalRatio',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clubstatistic',
            name='PharmacyRatio',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clubstatistic',
            name='Ratio20',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
