# Generated by Django 3.0.4 on 2020-06-25 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Server_app', '0027_auto_20200624_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='uID',
            field=models.CharField(max_length=80),
        ),
    ]
